### ISSUE TITLE
warning in Logfile

### ISSUE THREAD

**Issue by erichsch** [ioBroker/ioBroker.maxcube#20] opened 2020-05-08 08:45 UTC
maxcube.0 | 2020-05-08 10:41:43.620 | warn | (14583) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!
-- | -- | -- | --

**Comment by thost96** [comment] 2020-06-01 08:46
duplicate of issue #18

**Closed** 2020-06-01 11:51 UTC
